version: '3'

services:
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
    networks:
      default:
        aliases:
          - mailcatcher
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "" # Vide, car aucun mot de passe n'est défini pour root
      MYSQL_DATABASE: hack
    ports:
      - "3307:3306"
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
